/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.javaj2eefsd.workshop.api;

import javax.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import com.javaj2eefsd.workshop.model.UserDetail;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-06-06T07:36:56.089+05:30")

@Api(value = "login", description = "the login API")
public interface LoginApi {

    @ApiOperation(value = "Authenticate a valid user.", nickname = "loginUser", notes = "Authenticate a valid user", tags={ "login", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "User Authentication successful."),
        @ApiResponse(code = 404, message = "User Authentication failed.") })
    @RequestMapping(value = "/login",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<?> loginUser(@ApiParam(value = "User needs to be authenticated. Password must be encrypted." ,required=true )  @Valid @RequestBody UserDetail body) throws Exception;

}
