/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.javaj2eefsd.workshop.api;

import io.swagger.annotations.*;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;

import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-06-06T07:36:56.089+05:30")

@Api(value = "sendEmail", description = "the sendEmail API")
public interface SendEmailApi {

    @ApiOperation(value = "Send OTP to user via emailId.", nickname = "sendEmailToUser", notes = "Send OTP to user via emailId. emailId is manadatory.", response = String.class, authorizations = {
        @Authorization(value = "bearerAuth")
    }, tags={ "register", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Send OTP mail.", response = String.class),
        @ApiResponse(code = 404, message = "Send OTP to user via emailId Failed.") })
    @RequestMapping(value = "/sendEmail",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<String> sendEmailToUser(@ApiParam(value = "Send OTP mail." ,required=true )  @RequestParam("emailId") String emailId, Integer otp) throws Exception;

}
