/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.javaj2eefsd.workshop.api;

import com.javaj2eefsd.workshop.model.UserCurrency;
import com.javaj2eefsd.workshop.model.UserPassword;
import com.javaj2eefsd.workshop.model.UserSettingsByEmailId;

import io.swagger.annotations.*;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;

import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-06-06T07:36:56.089+05:30")

@Api(value = "userSettings", description = "the userSettings API")
public interface UserSettingsApi {

    @ApiOperation(value = "modify your currency in settings screen", nickname = "userCurrencyUpdate", notes = "change your profile settings (Currency).", response = UserSettingsByEmailId.class, authorizations = {
        @Authorization(value = "bearerAuth")
    }, tags={ "settings", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "User information successfully updated to database.", response = UserSettingsByEmailId.class),
        @ApiResponse(code = 404, message = "User information failed to be updated to database.") })
    @RequestMapping(value = "/userSettings/currencyUpdate",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<UserSettingsByEmailId> userCurrencyUpdate(@ApiParam(value = "User Profile Settings - Change Currency." ,required=true )  @Valid @RequestBody UserCurrency usercurrencymodel) throws Exception;


    @ApiOperation(value = "modify your password in settings screen", nickname = "userPasswordUpdate", notes = "change your profile settings (Password).", response = UserSettingsByEmailId.class, authorizations = {
        @Authorization(value = "bearerAuth")
    }, tags={ "settings", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "User Password information successfully updated to database.", response = UserSettingsByEmailId.class),
        @ApiResponse(code = 404, message = "User Password information failed to be updated to database.") })
    @RequestMapping(value = "/userSettings/passwordUpdate",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<UserSettingsByEmailId> userPasswordUpdate(@ApiParam(value = "User Profile Settings - Change Password." ,required=true )  @Valid @RequestBody UserPassword userpasswordmodel) throws Exception;

}
